"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AdminLanguage = "en" | "fa" | "ps";
export type AdminThemeMode = "light" | "dark" | "system";

export const DEFAULT_ACCENT = "#696cff";

const fa: Record<string, string> = {
  "Dashboard": "داشبورد",
  "Projects": "پروژه‌ها",
  "Project Categories": "کتگوری‌های پروژه",
  "Categories": "کتگوری‌ها",
  "Services": "خدمات",
  "Homepage Statistics": "آمار صفحه اصلی",
  "Statistics": "آمار",
  "Partners": "شرکا",
  "Testimonials": "دیدگاه‌ها",
  "Contact Inbox": "پیام‌های تماس",
  "Media Library": "کتابخانه رسانه",
  "Site Settings": "تنظیمات وب‌سایت",
  "Audit Log": "ثبت فعالیت‌ها",
  "Users & Roles": "کاربران و نقش‌ها",
  "My Profile": "پروفایل من",
  "Content management": "مدیریت محتوا",
  "Communication & media": "ارتباطات و رسانه",
  "Administration": "مدیریت سیستم",
  "Account": "حساب کاربری",
  "Search": "جستجو",
  "Search (Ctrl+/)": "جستجو (Ctrl+/)",
  "Home": "خانه",
  "Sign out": "خروج",
  "CMS online": "CMS آنلاین",
  "Secure admin workspace": "محیط امن مدیریت",
  "Professional content administration": "مدیریت حرفه‌ای محتوا",
  "Language": "زبان",
  "English": "انگلیسی",
  "Dari": "دری",
  "Pashto": "پشتو",
  "Content module": "بخش محتوا",
  "Add new": "افزودن جدید",
  "Total records": "مجموع رکوردها",
  "Showing": "نمایش",
  "of": "از",
  "Record": "رکورد",
  "Status": "وضعیت",
  "Order": "ترتیب",
  "Updated": "به‌روزرسانی",
  "Actions": "عملیات",
  "Edit": "ویرایش",
  "Delete": "حذف",
  "Save changes": "ذخیره تغییرات",
  "Saving…": "در حال ذخیره…",
  "Cancel": "لغو",
  "Close": "بستن",
  "Create record": "ایجاد رکورد",
  "Edit record": "ویرایش رکورد",
  "Multilingual": "چندزبانه",
  "One item per line": "هر مورد در یک خط",
  "Enable or disable this option.": "این گزینه را فعال یا غیرفعال کنید.",
  "Cloudinary URL": "آدرس Cloudinary",
  "Select…": "انتخاب…",
  "No records found.": "هیچ رکوردی یافت نشد.",
  "Changes saved successfully.": "تغییرات با موفقیت ذخیره شد.",
  "Asset management": "مدیریت رسانه",
  "Manage Cloudinary-backed images and documents used across the website.": "تصاویر و اسناد ذخیره‌شده در Cloudinary را مدیریت کنید.",
  "files": "فایل",
  "Upload media": "آپلود رسانه",
  "Upload new media": "آپلود رسانه جدید",
  "Choose file": "انتخاب فایل",
  "Upload": "آپلود",
  "Uploading…": "در حال آپلود…",
  "Library": "کتابخانه",
  "Copy URL": "کاپی آدرس",
  "Copied": "کاپی شد",
  "No media files": "هیچ فایل رسانه‌ای موجود نیست",
  "Delete media": "حذف رسانه",
  "Visitor communication": "ارتباط با بازدیدکنندگان",
  "messages": "پیام",
  "All messages": "همه پیام‌ها",
  "New": "جدید",
  "In progress": "در حال پیگیری",
  "Replied": "پاسخ داده‌شده",
  "Archived": "آرشیف‌شده",
  "Spam": "اسپم",
  "Messages": "پیام‌ها",
  "No messages found.": "هیچ پیامی یافت نشد.",
  "Message details": "جزئیات پیام",
  "Internal note": "یادداشت داخلی",
  "Save note": "ذخیره یادداشت",
  "Access management": "مدیریت دسترسی",
  "Add user": "افزودن کاربر",
  "Total users": "مجموع کاربران",
  "Active accounts": "حساب‌های فعال",
  "Administrators": "مدیران",
  "CMS users": "کاربران CMS",
  "User": "کاربر",
  "Role": "نقش",
  "Last login": "آخرین ورود",
  "Name": "نام",
  "Email": "ایمیل",
  "Temporary password": "رمز موقت",
  "New password (optional)": "رمز جدید (اختیاری)",
  "Content Editor": "ویرایشگر محتوا",
  "Admin": "مدیر",
  "Super Admin": "مدیر ارشد",
  "Active account": "حساب فعال",
  "Require password change": "الزام تغییر رمز",
  "Save user": "ذخیره کاربر",
  "Create account": "ایجاد حساب",
  "Account settings": "تنظیمات حساب",
  "Website configuration": "تنظیمات وب‌سایت",
  "Save all settings": "ذخیره همه تنظیمات",
  "Settings": "تنظیمات",
  "Company": "شرکت",
  "Homepage": "صفحه اصلی",
  "Navigation": "منوی وب‌سایت",
  "Footer": "فوتر",
  "SEO": "SEO",
  "Company information": "اطلاعات شرکت",
  "Homepage content": "محتوای صفحه اصلی",
  "Navigation labels": "عنوان‌های منو",
  "Footer content": "محتوای فوتر",
  "SEO & social sharing": "SEO و اشتراک‌گذاری اجتماعی",
  "Save settings": "ذخیره تنظیمات",
  "Site settings": "تنظیمات وب‌سایت",
  "Activity history": "تاریخچه فعالیت",
  "Date": "تاریخ",
  "Administrator": "مدیر",
  "Action": "عملیات",
  "Resource": "منبع",
  "Record ID": "شناسه رکورد",
  "events": "رویداد",
  "No audit events yet.": "هنوز رویدادی ثبت نشده است.",
  "Profile": "پروفایل",
  "Profile photo": "عکس پروفایل",
  "Upload profile photo": "آپلود عکس پروفایل",
  "Account details": "جزئیات حساب",
  "Your identity used throughout the administration panel.": "مشخصات شما که در سراسر پنل مدیریت استفاده می‌شود.",
  "Full name": "نام کامل",
  "Profile image Cloudinary URL": "آدرس Cloudinary عکس پروفایل",
  "Appearance & language": "ظاهر و زبان",
  "Choose the CMS language, display mode and primary color for your account.": "زبان CMS، حالت نمایش و رنگ اصلی حساب خود را انتخاب کنید.",
  "Display mode": "حالت نمایش",
  "Light": "روشن",
  "Dark": "تاریک",
  "System": "سیستم",
  "Primary color": "رنگ اصلی",
  "Custom color": "رنگ دلخواه",
  "Save profile": "ذخیره پروفایل",
  "Profile details updated successfully.": "اطلاعات پروفایل با موفقیت به‌روزرسانی شد.",
  "Password & security": "رمز و امنیت",
  "Current password": "رمز فعلی",
  "New password": "رمز جدید",
  "Confirm new password": "تأیید رمز جدید",
  "Change password": "تغییر رمز",
  "Password changed successfully.": "رمز با موفقیت تغییر کرد.",
  "Active": "فعال",
  "Disabled": "غیرفعال",
  "Security": "امنیت",
  "Protected": "محافظت‌شده",
  "Action required": "نیازمند اقدام",
  "Current session": "نشست فعلی",
  "Welcome back": "خوش آمدید",
  "Sign in to your account": "به حساب خود وارد شوید",
  "Password": "رمز عبور",
  "Sign in": "ورود",
  "Signing in…": "در حال ورود…",
  "Change your password": "رمز عبور خود را تغییر دهید",
  "Update password": "به‌روزرسانی رمز",
  "Updating…": "در حال به‌روزرسانی…",
  "Theme color": "رنگ قالب",
  "Open": "باز کردن",
  "View": "مشاهده",
  "Published": "منتشرشده",
  "Draft": "پیش‌نویس",
  "Inactive": "غیرفعال",
  "Never": "هرگز",
  "Media": "رسانه",
  "Users": "کاربران",
  "Slug": "نامک (Slug)",
  "Category slug": "نامک کتگوری",
  "Donor / Client": "تمویل‌کننده / مشتری",
  "Project period": "دوره پروژه",
  "Project title": "عنوان پروژه",
  "Location": "موقعیت",
  "Beneficiaries": "مستفیدشوندگان",
  "Short description": "توضیح کوتاه",
  "Full description": "توضیح کامل",
  "Key outcomes": "نتایج کلیدی",
  "Cover image": "تصویر اصلی",
  "Gallery images": "تصاویر گالری",
  "Featured project": "پروژه برجسته",
  "Display order": "ترتیب نمایش",
  "Publication status": "وضعیت نشر",
  "Category name": "نام کتگوری",
  "Icon key": "کلید آیکن",
  "Service title": "عنوان خدمت",
  "Description": "توضیحات",
  "Translation key": "کلید ترجمه",
  "Displayed value": "مقدار نمایشی",
  "Label": "عنوان",
  "Partner name": "نام شریک",
  "Partner type": "نوع شریک",
  "UN agency": "اداره ملل متحد",
  "International NGO": "مؤسسه بین‌المللی",
  "National NGO": "مؤسسه ملی",
  "Government": "دولت",
  "Other": "سایر",
  "Logo": "لوگو",
  "Website URL": "آدرس وب‌سایت",
  "Quote": "دیدگاه",
  "Author / role": "نویسنده / وظیفه",
  "Organization": "اداره",
  "Photo / logo": "عکس / لوگو",
  "Company name": "نام شرکت",
  "Short name": "نام کوتاه",
  "Tagline": "شعار",
  "Established year": "سال تأسیس",
  "Registration number": "شماره ثبت",
  "Primary phone": "شماره تماس اصلی",
  "Secondary phone": "شماره تماس دوم",
  "General email": "ایمیل عمومی",
  "Tender email": "ایمیل داوطلبی",
  "Logo Cloudinary URL": "آدرس Cloudinary لوگو",
  "Favicon Cloudinary URL": "آدرس Cloudinary فاویکن",
  "Office address": "آدرس دفتر",
  "Working hours": "ساعات کاری",
  "Provincial offices": "دفاتر ولایتی",
  "Hero section": "بخش اصلی",
  "About section": "بخش درباره ما",
  "Badge": "نشان",
  "Title line 1": "خط اول عنوان",
  "Highlighted title": "عنوان برجسته",
  "Subtitle": "زیرعنوان",
  "Primary CTA": "دکمه اصلی",
  "Secondary CTA": "دکمه دوم",
  "Hero image Cloudinary URL": "آدرس Cloudinary تصویر اصلی",
  "Kicker": "عنوان کوچک",
  "Italic prefix": "پیشوند عنوان",
  "Title": "عنوان",
  "Paragraph 1": "پاراگراف ۱",
  "Paragraph 2": "پاراگراف ۲",
  "About image 1 URL": "آدرس تصویر اول درباره ما",
  "About image 2 URL": "آدرس تصویر دوم درباره ما",
  "About": "درباره ما",
  "Contact": "تماس",
  "Request CTA": "دکمه درخواست",
  "About text": "متن درباره ما",
  "Registration text": "متن ثبت",
  "Quick links heading": "عنوان لینک‌های سریع",
  "Services heading": "عنوان خدمات",
  "Contact heading": "عنوان تماس",
  "Rights text": "متن حقوق نشر",
  "Meta title": "عنوان متا",
  "Meta description": "توضیحات متا",
  "Keywords": "واژه‌های کلیدی",
  "Open Graph image URL": "آدرس تصویر Open Graph",
  "Identity and contact information": "هویت و اطلاعات تماس",
  "Hero and about content": "محتوای بخش اصلی و درباره ما",
  "Menu labels": "عنوان‌های منو",
  "Footer content and labels": "محتوا و عنوان‌های فوتر",
  "Search and social metadata": "متادیتای جستجو و شبکه‌های اجتماعی",
  "Monitor content and access the most important administration workflows.": "محتوا و مهم‌ترین روندهای کاری مدیریت را بررسی کنید.",
  "Publishing overview": "نمای کلی نشر",
  "Quick actions": "عملیات سریع",
  "Recent activity": "فعالیت‌های اخیر",
  "Content distribution": "توزیع محتوا",
  "Create project": "ایجاد پروژه",
  "Add a portfolio entry": "افزودن پروژه به نمونه‌کارها",
  "Add images or documents": "افزودن تصویر یا سند",
  "Company, homepage and SEO": "شرکت، صفحه اصلی و SEO",
  "View audit log": "مشاهده ثبت فعالیت‌ها",
  "Open inbox": "باز کردن پیام‌ها",
  "Review content": "بررسی محتوا",
  "Review projects": "بررسی پروژه‌ها",
  "Active users": "کاربران فعال",
  "New messages": "پیام‌های جدید",
  "Settings saved successfully.": "تنظیمات با موفقیت ذخیره شد.",
  "Select a record to edit its content.": "برای ویرایش محتوا یک رکورد را انتخاب کنید.",
  "Update the fields below. Multilingual values are stored separately.": "فیلدهای زیر را ویرایش کنید. مقادیر چندزبانه جداگانه ذخیره می‌شوند.",
  "Manage company details, homepage content, navigation, footer information and SEO.": "جزئیات شرکت، محتوای صفحه اصلی، منو، فوتر و SEO را مدیریت کنید.",
  "Main homepage introduction and calls to action.": "معرفی اصلی صفحه نخست و دکمه‌های اقدام.",
  "Homepage organization introduction and imagery.": "معرفی اداره و تصاویر بخش درباره ما در صفحه اصلی.",
  "Changes are saved only when you click the button.": "تغییرات فقط با کلیک روی دکمه ذخیره می‌شوند.",
  "Your website administration workspace is ready. Review publishing progress, media, messages and recent activity from here.": "محیط مدیریت وب‌سایت آماده است. وضعیت نشر، رسانه‌ها، پیام‌ها و فعالیت‌های اخیر را از اینجا بررسی کنید.",
  "Contact form inbox": "پیام‌های فورم تماس",
  "Current project publication coverage.": "وضعیت فعلی نشر پروژه‌ها.",
  "Common administration tasks.": "کارهای معمول مدیریت.",
  "Latest recorded changes in the CMS.": "آخرین تغییرات ثبت‌شده در CMS.",
  "Record volume by module.": "تعداد رکوردها به تفکیک بخش.",

  "published": "نشرشده",
  "Website services": "خدمات وب‌سایت",
  "Partner records": "سوابق شرکا",
  "Stored assets": "فایل‌های ذخیره‌شده",
  "Live data": "معلومات زنده",
  "Published projects": "پروژه‌های نشرشده",
  "Other project states": "سایر وضعیت‌های پروژه",
  "Total projects": "مجموع پروژه‌ها",
  "Loading recent activity…": "در حال بارگذاری فعالیت‌های اخیر…",
  "No activity has been recorded yet.": "هنوز هیچ فعالیتی ثبت نشده است.",
  "Upload an image to Cloudinary through the existing Media Library API, or paste an existing secure Cloudinary URL below.": "یک تصویر را از طریق API موجود کتابخانه رسانه به Cloudinary آپلود کنید، یا یک آدرس امن موجود Cloudinary را در پایین وارد کنید.",
  "Email changes remain controlled by Users & Roles.": "تغییر ایمیل همچنان از بخش کاربران و نقش‌ها مدیریت می‌شود.",
  "You can paste a Cloudinary HTTPS image URL directly.": "می‌توانید آدرس HTTPS تصویر Cloudinary را مستقیماً وارد کنید.",
  "Change your password without affecting your profile preferences.": "رمز عبور خود را بدون تغییر تنظیمات پروفایل عوض کنید.",
  "Copy asset URLs for use in CMS content fields.": "آدرس فایل‌ها را برای استفاده در بخش‌های محتوای CMS کاپی کنید.",
  "Upload your first image or PDF.": "اولین تصویر یا فایل PDF خود را آپلود کنید.",
  "Images and PDF documents up to 10 MB are stored in Cloudinary.": "تصاویر و اسناد PDF تا ۱۰ مگابایت در Cloudinary ذخیره می‌شوند.",
  "JPEG, PNG, WebP, AVIF, GIF or PDF · maximum 10 MB": "JPEG، PNG، WebP، AVIF، GIF یا PDF · حداکثر ۱۰ مگابایت",
  "Review and manage messages submitted through the public website contact form.": "پیام‌های ارسال‌شده از فورم تماس وب‌سایت عمومی را بررسی و مدیریت کنید.",
  "Select a message to open its details.": "برای دیدن جزئیات، یک پیام را انتخاب کنید.",
  "Reply by email": "پاسخ با ایمیل",
  "Subject": "موضوع",
  "Received": "دریافت‌شده",
  "Website inquiry": "درخواست وب‌سایت",
  "Add a private note for administrators…": "یک یادداشت خصوصی برای مدیران اضافه کنید…",
  "Create CMS administrators and editors, manage roles, and control account access.": "مدیران و ویرایشگران CMS را ایجاد کنید، نقش‌ها را مدیریت کنید و دسترسی حساب‌ها را کنترول کنید.",
  "Accounts with access to administration.": "حساب‌هایی که به بخش مدیریت دسترسی دارند.",
  "No users found.": "هیچ کاربری یافت نشد.",
  "Configure identity, credentials and CMS role.": "مشخصات، اطلاعات ورود و نقش CMS را تنظیم کنید.",
  "Allow this user to sign in.": "به این کاربر اجازه ورود بدهید.",
  "Prompt the user to set a new password on next sign-in.": "در ورود بعدی، کاربر را ملزم به تعیین رمز عبور جدید کنید.",
  "Administration history": "تاریخچه مدیریت",
  "Review recorded administrative actions by user, resource, and date.": "فعالیت‌های ثبت‌شده مدیریتی را بر اساس کاربر، منبع و تاریخ بررسی کنید.",
  "Most recent administrative events are shown first.": "جدیدترین رویدادهای مدیریتی در ابتدا نمایش داده می‌شوند.",
  "Theme color hex value": "کُد رنگ قالب",
  "Theme": "قالب",
  "Content Management System": "سیستم مدیریت محتوا",
  "Secure administration": "مدیریت امن",
  "Manage your website from one professional workspace.": "وب‌سایت خود را از یک محیط حرفه‌ای مدیریت کنید.",
  "Control projects, services, media, contact messages, multilingual content and website settings.": "پروژه‌ها، خدمات، رسانه‌ها، پیام‌های تماس، محتوای چندزبانه و تنظیمات وب‌سایت را مدیریت کنید.",
  "Maintain published website information.": "معلومات نشرشده وب‌سایت را مدیریت کنید.",
  "Media library": "کتابخانه رسانه",
  "Organize Cloudinary-backed assets.": "فایل‌های ذخیره‌شده در Cloudinary را تنظیم کنید.",
  "Administrative control": "کنترول مدیریتی",
  "Role-based access and audit history.": "دسترسی مبتنی بر نقش و تاریخچه فعالیت‌ها.",
  "Authorized administrators only": "فقط مدیران مجاز",
  "Administrator access": "ورود مدیر",
  "Enter your administrator credentials to continue.": "برای ادامه، معلومات ورود مدیر را وارد کنید.",
  "Email address": "آدرس ایمیل",
  "Your session is protected by the existing CMS authentication system.": "نشست شما توسط سیستم احراز هویت موجود CMS محافظت می‌شود.",
  "Account security": "امنیت حساب",
  "Your administrator requires a new password before you can continue to the CMS.": "پیش از ادامه کار با CMS باید یک رمز عبور جدید تعیین کنید.",
  "Open navigation": "باز کردن منو",
  "CMS summary": "خلاصه CMS",
  "Check visitor messages": "بررسی پیام\u200cهای بازدیدکنندگان",
  "Close navigation": "بستن منو",
  "Tabiat Gran CMS dashboard": "داشبورد CMS طبیعت گران",
  "Admin navigation": "منوی مدیریت",
  "Open account menu": "باز کردن منوی حساب",
  "Media record removed. The Cloudinary asset was already missing.": "رکورد رسانه حذف شد؛ فایل Cloudinary از قبل موجود نبود.",
  "Media deleted from Cloudinary and the CMS library.": "رسانه از Cloudinary و کتابخانه CMS حذف شد.",
  "Delete failed": "حذف ناموفق بود",
  "Media uploaded successfully.": "رسانه با موفقیت آپلود شد.",
  "Profile photo uploaded. Save your profile to use it for your account.": "عکس پروفایل آپلود شد. برای استفاده در حساب، پروفایل را ذخیره کنید.",
  "New passwords do not match.": "رمزهای عبور جدید مطابقت ندارند.",
  "Content record": "رکورد محتوا",
  "One Cloudinary URL per line": "در هر خط یک آدرس Cloudinary",
  "Control public website menu labels in English, Dari and Pashto.": "عنوان‌های منوی وب‌سایت عمومی را به زبان‌های انگلیسی، دری و پشتو مدیریت کنید.",
  "Core identity, contact details, branding and office information.": "هویت اصلی، معلومات تماس، برند و معلومات دفتر.",
  "Define categories used to organize projects.": "کتگوری‌های مورد استفاده برای تنظیم پروژه‌ها را تعریف کنید.",
  "Edit organization information and footer labels displayed across the public website.": "معلومات اداره و عنوان‌های فوتر را که در وب‌سایت عمومی نمایش داده می‌شود ویرایش کنید.",
  "Edit the hero and about sections shown on the public homepage.": "بخش اصلی و درباره ما را که در صفحه اصلی وب‌سایت نمایش داده می‌شود ویرایش کنید.",
  "Keep the current format expected by the backend settings model.": "قالب فعلی مورد نیاز مدل تنظیمات بک‌اند را حفظ کنید.",
  "Manage UN agencies, INGOs, national NGOs and government partners.": "ادارات ملل متحد، مؤسسات بین‌المللی، مؤسسات ملی و شرکای دولتی را مدیریت کنید.",
  "Manage headline numbers such as years of experience, projects and beneficiaries.": "ارقام برجسته مانند سال‌های تجربه، پروژه‌ها و مستفیدشوندگان را مدیریت کنید.",
  "Manage metadata used by search engines and social platforms.": "متادیتای مورد استفاده موتورهای جستجو و شبکه‌های اجتماعی را مدیریت کنید.",
  "Manage partner/client testimonials displayed on the site.": "دیدگاه‌های شرکا و مشتریان را که در وب‌سایت نمایش داده می‌شود مدیریت کنید.",
  "Manage services presented on the public website.": "خدمات نمایش‌داده‌شده در وب‌سایت عمومی را مدیریت کنید.",
  "Manage the multilingual project portfolio, galleries, outcomes and publication state.": "پورتفولیوی چندزبانه پروژه‌ها، گالری‌ها، نتایج و وضعیت نشر را مدیریت کنید.",
  "Message status filter": "فلتر وضعیت پیام‌ها",
  "Paste the URL of the selected hero image from Media Library.": "آدرس تصویر اصلی انتخاب‌شده از کتابخانه رسانه را وارد کنید.",
  "Settings sections": "بخش‌های تنظیمات",
  "Use a square icon asset where possible.": "در صورت امکان از فایل آیکن مربع استفاده کنید.",
  "Use an asset URL from the Media Library.": "از آدرس فایل موجود در کتابخانه رسانه استفاده کنید.",
  "Used when the website is shared on social platforms.": "هنگام اشتراک‌گذاری وب‌سایت در شبکه‌های اجتماعی استفاده می‌شود.",
  "Unable to load dashboard": "بارگذاری داشبورد ممکن نشد",
  "Unable to load settings": "بارگذاری تنظیمات ممکن نشد",
  "Unable to load data": "بارگذاری معلومات ممکن نشد",
  "Unable to load messages": "بارگذاری پیام‌ها ممکن نشد",
  "Unable to load media": "بارگذاری رسانه‌ها ممکن نشد",
  "Unable to load audit log": "بارگذاری ثبت فعالیت‌ها ممکن نشد",
  "Unable to update profile": "به‌روزرسانی پروفایل ممکن نشد",
  "Unable to change password": "تغییر رمز عبور ممکن نشد",
  "Profile image upload failed": "آپلود عکس پروفایل ناموفق بود",
  "Sign in failed": "ورود ناموفق بود",
  "New passwords do not match": "رمزهای عبور جدید مطابقت ندارند",
  "Save failed": "ذخیره ناموفق بود",
  "Update failed": "به‌روزرسانی ناموفق بود",
  "Upload failed": "آپلود ناموفق بود",
  "Account not found": "حساب کاربری یافت نشد",
  "A record with this unique value already exists": "رکوردی با این مقدار یکتا از قبل وجود دارد",
  "Cloudinary did not confirm deletion": "Cloudinary حذف فایل را تأیید نکرد",
  "Cloudinary environment variables are not configured": "متغیرهای محیطی Cloudinary تنظیم نشده‌اند",
  "Cloudinary upload failed": "آپلود به Cloudinary ناموفق بود",
  "Current password is incorrect": "رمز عبور فعلی نادرست است",
  "File exceeds 10 MB": "حجم فایل بیشتر از ۱۰ مگابایت است",
  "File is required": "انتخاب فایل الزامی است",
  "Forbidden": "دسترسی مجاز نیست",
  "Invalid credentials": "معلومات ورود نادرست است",
  "Invalid email or password": "ایمیل یا رمز عبور نادرست است",
  "Invalid message update": "به‌روزرسانی پیام معتبر نیست",
  "Invalid request data": "معلومات درخواست معتبر نیست",
  "Not found": "مورد یافت نشد",
  "Unknown resource": "منبع ناشناخته است",
  "Unsupported file type": "نوع فایل پشتیبانی نمی‌شود",
  "Your role cannot publish content": "نقش شما اجازه نشر محتوا را ندارد",
  "Create": "ایجاد",
  "Update": "به‌روزرسانی",
  "Untitled record": "رکورد بدون عنوان",
  "Enter your password": "رمز عبور خود را وارد کنید",
  "Uploaded media": "رسانه آپلودشده",
  "Settings section navigation": "منوی بخش‌های تنظیمات",
  "Selected media preview": "پیش‌نمایش رسانه انتخاب‌شده",
  "AUTH_SECRET must be at least 32 characters": "کلید امنیتی سیستم باید حداقل ۳۲ کاراکتر باشد",
  "CMS data unavailable": "داده‌های CMS در دسترس نیست",
  "MONGODB_URI is not configured": "اتصال دیتابیس MongoDB تنظیم نشده است",
  "New password must be different from the current password": "رمز جدید باید با رمز فعلی متفاوت باشد",
  "Origin not allowed": "مبدأ این درخواست مجاز نیست",
  "Password change required": "تغییر رمز عبور الزامی است",
  "Please check the form fields": "لطفاً فیلدهای فورم را بررسی کنید",
  "Projects unavailable": "پروژه‌ها در دسترس نیستند",
  "Too many login attempts. Try again later.": "تلاش‌های ورود بیش از حد است. بعداً دوباره کوشش کنید.",
  "Too many messages. Try again later.": "پیام‌های بیش از حد ارسال شده است. بعداً دوباره کوشش کنید.",
  "Unable to sign in": "ورود به حساب انجام نشد",
  "Unable to submit message": "ارسال پیام انجام نشد",
  "Unauthorized": "شما اجازه دسترسی ندارید",
  "Use a new password of 10–72 characters.": "یک رمز جدید بین ۱۰ تا ۷۲ کاراکتر انتخاب کنید.",
  "Validation failed": "اعتبارسنجی ناموفق بود",
  "You cannot delete your own account": "نمی‌توانید حساب خودتان را حذف کنید",
  "You cannot disable or demote your own account": "نمی‌توانید حساب خودتان را غیرفعال کنید یا سطح دسترسی آن را کاهش دهید",
};

const ps: Record<string, string> = {
  "Dashboard": "ډشبورډ",
  "Projects": "پروژې",
  "Project Categories": "د پروژو کټګورۍ",
  "Categories": "کټګورۍ",
  "Services": "خدمتونه",
  "Homepage Statistics": "د کورپاڼې احصایې",
  "Statistics": "احصایې",
  "Partners": "شریکان",
  "Testimonials": "د مراجعینو نظرونه",
  "Contact Inbox": "د اړیکو صندوق",
  "Media Library": "رسنیز کتابتون",
  "Site Settings": "د وېب‌سایټ تنظیمات",
  "Audit Log": "د فعالیتونو ثبت",
  "Users & Roles": "کاروونکي او رولونه",
  "My Profile": "زما پروفایل",
  "Content management": "د منځپانګې مدیریت",
  "Communication & media": "اړیکې او رسنۍ",
  "Administration": "د سیستم مدیریت",
  "Account": "حساب",
  "Search": "لټون",
  "Search (Ctrl+/)": "لټون (Ctrl+/)",
  "Home": "کور",
  "Sign out": "وتل",
  "CMS online": "CMS آنلاین",
  "Secure admin workspace": "خوندي اداري چاپېریال",
  "Professional content administration": "مسلکي منځپانګه مدیریت",
  "Language": "ژبه",
  "English": "انګلیسي",
  "Dari": "دري",
  "Pashto": "پښتو",
  "Content module": "د منځپانګې برخه",
  "Add new": "نوی زیات کړئ",
  "Total records": "ټول ریکارډونه",
  "Showing": "ښودل کېږي",
  "of": "له",
  "Record": "ریکارډ",
  "Status": "حالت",
  "Order": "ترتیب",
  "Updated": "تازه شوی",
  "Actions": "عملیات",
  "Edit": "سمون",
  "Delete": "ړنګول",
  "Save changes": "بدلونونه خوندي کړئ",
  "Saving…": "خوندي کېږي…",
  "Cancel": "لغوه",
  "Close": "تړل",
  "Create record": "ریکارډ جوړول",
  "Edit record": "ریکارډ سمول",
  "Multilingual": "څو ژبیز",
  "One item per line": "هر توکی په یوه کرښه",
  "Enable or disable this option.": "دا انتخاب فعال یا غیرفعال کړئ.",
  "Cloudinary URL": "د Cloudinary پته",
  "Select…": "وټاکئ…",
  "No records found.": "هیڅ ریکارډ ونه موندل شو.",
  "Changes saved successfully.": "بدلونونه په بریالیتوب خوندي شول.",
  "Asset management": "د رسنیو مدیریت",
  "Manage Cloudinary-backed images and documents used across the website.": "په Cloudinary کې خوندي انځورونه او اسناد مدیریت کړئ.",
  "files": "فایلونه",
  "Upload media": "رسنۍ پورته کړئ",
  "Upload new media": "نوې رسنۍ پورته کړئ",
  "Choose file": "فایل وټاکئ",
  "Upload": "پورته کول",
  "Uploading…": "پورته کېږي…",
  "Library": "کتابتون",
  "Copy URL": "پته کاپي کړئ",
  "Copied": "کاپي شو",
  "No media files": "رسنیز فایلونه نشته",
  "Delete media": "رسنۍ ړنګول",
  "Visitor communication": "له لیدونکو سره اړیکې",
  "messages": "پیغامونه",
  "All messages": "ټول پیغامونه",
  "New": "نوي",
  "In progress": "د تعقیب لاندې",
  "Replied": "ځواب شوي",
  "Archived": "آرشیف شوي",
  "Spam": "سپیم",
  "Messages": "پیغامونه",
  "No messages found.": "هیڅ پیغام ونه موندل شو.",
  "Message details": "د پیغام جزیات",
  "Internal note": "داخلي یادښت",
  "Save note": "یادښت خوندي کړئ",
  "Access management": "د لاسرسي مدیریت",
  "Add user": "کاروونکی زیات کړئ",
  "Total users": "ټول کاروونکي",
  "Active accounts": "فعال حسابونه",
  "Administrators": "مدیران",
  "CMS users": "د CMS کاروونکي",
  "User": "کاروونکی",
  "Role": "رول",
  "Last login": "وروستی ننوتل",
  "Name": "نوم",
  "Email": "برېښنالیک",
  "Temporary password": "لنډمهاله پټنوم",
  "New password (optional)": "نوی پټنوم (اختیاري)",
  "Content Editor": "د منځپانګې سمونګر",
  "Admin": "مدیر",
  "Super Admin": "لوړ مدیر",
  "Active account": "فعال حساب",
  "Require password change": "د پټنوم بدلون اړین کړئ",
  "Save user": "کاروونکی خوندي کړئ",
  "Create account": "حساب جوړول",
  "Account settings": "د حساب تنظیمات",
  "Website configuration": "د وېب‌سایټ تنظیمات",
  "Save all settings": "ټول تنظیمات خوندي کړئ",
  "Settings": "تنظیمات",
  "Company": "شرکت",
  "Homepage": "کورپاڼه",
  "Navigation": "د وېب‌سایټ مېنو",
  "Footer": "فوټر",
  "SEO": "SEO",
  "Company information": "د شرکت معلومات",
  "Homepage content": "د کورپاڼې منځپانګه",
  "Navigation labels": "د مېنو سرلیکونه",
  "Footer content": "د فوټر منځپانګه",
  "SEO & social sharing": "SEO او ټولنیز شریکول",
  "Save settings": "تنظیمات خوندي کړئ",
  "Site settings": "د وېب‌سایټ تنظیمات",
  "Activity history": "د فعالیت تاریخچه",
  "Date": "نېټه",
  "Administrator": "مدیر",
  "Action": "عمل",
  "Resource": "سرچینه",
  "Record ID": "د ریکارډ پېژند",
  "events": "پېښې",
  "No audit events yet.": "تر اوسه فعالیت نه دی ثبت شوی.",
  "Profile": "پروفایل",
  "Profile photo": "د پروفایل انځور",
  "Upload profile photo": "د پروفایل انځور پورته کړئ",
  "Account details": "د حساب جزیات",
  "Your identity used throughout the administration panel.": "ستاسو پېژندنه چې په ټول اداري پینل کې کارېږي.",
  "Full name": "بشپړ نوم",
  "Profile image Cloudinary URL": "د پروفایل انځور Cloudinary پته",
  "Appearance & language": "بڼه او ژبه",
  "Choose the CMS language, display mode and primary color for your account.": "د خپل حساب لپاره د CMS ژبه، د ښودلو حالت او اصلي رنګ وټاکئ.",
  "Display mode": "د ښودلو حالت",
  "Light": "روښانه",
  "Dark": "تیاره",
  "System": "سیستم",
  "Primary color": "اصلي رنګ",
  "Custom color": "ځانګړی رنګ",
  "Save profile": "پروفایل خوندي کړئ",
  "Profile details updated successfully.": "د پروفایل معلومات په بریالیتوب تازه شول.",
  "Password & security": "پټنوم او امنیت",
  "Current password": "اوسنی پټنوم",
  "New password": "نوی پټنوم",
  "Confirm new password": "نوی پټنوم تایید کړئ",
  "Change password": "پټنوم بدل کړئ",
  "Password changed successfully.": "پټنوم په بریالیتوب بدل شو.",
  "Active": "فعال",
  "Disabled": "غیرفعال",
  "Security": "امنیت",
  "Protected": "خوندي",
  "Action required": "اقدام ته اړتیا ده",
  "Current session": "اوسنۍ ناسته",
  "Welcome back": "بیا ښه راغلاست",
  "Sign in to your account": "خپل حساب ته ننوځئ",
  "Password": "پټنوم",
  "Sign in": "ننوتل",
  "Signing in…": "ننوتل روان دي…",
  "Change your password": "خپل پټنوم بدل کړئ",
  "Update password": "پټنوم تازه کړئ",
  "Updating…": "تازه کېږي…",
  "Theme color": "د قالب رنګ",
  "Open": "پرانیستل",
  "View": "کتل",
  "Published": "خپور شوی",
  "Draft": "مسوده",
  "Inactive": "غیرفعال",
  "Never": "هېڅکله",
  "Media": "رسنۍ",
  "Users": "کاروونکي",
  "Slug": "Slug",
  "Category slug": "د کټګورۍ Slug",
  "Donor / Client": "تمویلوونکی / مراجع",
  "Project period": "د پروژې موده",
  "Project title": "د پروژې سرلیک",
  "Location": "موقعیت",
  "Beneficiaries": "ګټه اخیستونکي",
  "Short description": "لنډ تشریح",
  "Full description": "بشپړ تشریح",
  "Key outcomes": "مهمې پایلې",
  "Cover image": "اصلي انځور",
  "Gallery images": "د ګالري انځورونه",
  "Featured project": "ځانګړې پروژه",
  "Display order": "د ښودلو ترتیب",
  "Publication status": "د خپرېدو حالت",
  "Category name": "د کټګورۍ نوم",
  "Icon key": "د آیکن کیلي",
  "Service title": "د خدمت سرلیک",
  "Description": "تشریح",
  "Translation key": "د ژباړې کیلي",
  "Displayed value": "ښودل کېدونکی ارزښت",
  "Label": "سرلیک",
  "Partner name": "د شریک نوم",
  "Partner type": "د شریک ډول",
  "UN agency": "د ملګرو ملتونو اداره",
  "International NGO": "نړیواله موسسه",
  "National NGO": "ملي موسسه",
  "Government": "حکومت",
  "Other": "نور",
  "Logo": "لوګو",
  "Website URL": "د وېب‌سایټ پته",
  "Quote": "نظر",
  "Author / role": "لیکوال / دنده",
  "Organization": "اداره",
  "Photo / logo": "انځور / لوګو",
  "Company name": "د شرکت نوم",
  "Short name": "لنډ نوم",
  "Tagline": "شعار",
  "Established year": "د جوړېدو کال",
  "Registration number": "د ثبت شمېره",
  "Primary phone": "اصلي تلیفون",
  "Secondary phone": "دوهم تلیفون",
  "General email": "عمومي برېښنالیک",
  "Tender email": "د داوطلبۍ برېښنالیک",
  "Logo Cloudinary URL": "د لوګو Cloudinary پته",
  "Favicon Cloudinary URL": "د فاویکن Cloudinary پته",
  "Office address": "د دفتر پته",
  "Working hours": "کاري ساعتونه",
  "Provincial offices": "ولایتي دفترونه",
  "Hero section": "اصلي برخه",
  "About section": "زموږ په اړه برخه",
  "Badge": "نښه",
  "Title line 1": "د سرلیک لومړۍ کرښه",
  "Highlighted title": "ځانګړی سرلیک",
  "Subtitle": "فرعي سرلیک",
  "Primary CTA": "اصلي تڼۍ",
  "Secondary CTA": "دوهمه تڼۍ",
  "Hero image Cloudinary URL": "د اصلي انځور Cloudinary پته",
  "Kicker": "کوچنی سرلیک",
  "Italic prefix": "د سرلیک مخکینی متن",
  "Title": "سرلیک",
  "Paragraph 1": "پراګراف ۱",
  "Paragraph 2": "پراګراف ۲",
  "About image 1 URL": "د زموږ په اړه لومړي انځور پته",
  "About image 2 URL": "د زموږ په اړه دوهم انځور پته",
  "About": "زموږ په اړه",
  "Contact": "اړیکه",
  "Request CTA": "د غوښتنې تڼۍ",
  "About text": "د زموږ په اړه متن",
  "Registration text": "د ثبت متن",
  "Quick links heading": "د چټکو لینکونو سرلیک",
  "Services heading": "د خدمتونو سرلیک",
  "Contact heading": "د اړیکو سرلیک",
  "Rights text": "د حقوقو متن",
  "Meta title": "Meta سرلیک",
  "Meta description": "Meta تشریح",
  "Keywords": "کلیدي کلمې",
  "Open Graph image URL": "د Open Graph انځور پته",
  "Identity and contact information": "هویت او د اړیکو معلومات",
  "Hero and about content": "د اصلي او زموږ په اړه برخو منځپانګه",
  "Menu labels": "د مېنو سرلیکونه",
  "Footer content and labels": "د فوټر منځپانګه او سرلیکونه",
  "Search and social metadata": "د لټون او ټولنیزو شبکو مېټاډاټا",
  "Monitor content and access the most important administration workflows.": "منځپانګه او مهم اداري کاري بهیرونه وڅارئ.",
  "Publishing overview": "د خپرېدو عمومي کتنه",
  "Quick actions": "چټک عملیات",
  "Recent activity": "وروستي فعالیتونه",
  "Content distribution": "د منځپانګې وېش",
  "Create project": "پروژه جوړه کړئ",
  "Add a portfolio entry": "پورتفولیو ته پروژه زیاته کړئ",
  "Add images or documents": "انځورونه یا اسناد زیات کړئ",
  "Company, homepage and SEO": "شرکت، کورپاڼه او SEO",
  "View audit log": "د فعالیتونو ثبت وګورئ",
  "Open inbox": "صندوق پرانیزئ",
  "Review content": "منځپانګه وګورئ",
  "Review projects": "پروژې وګورئ",
  "Active users": "فعال کاروونکي",
  "New messages": "نوي پیغامونه",
  "Settings saved successfully.": "تنظیمات په بریالیتوب خوندي شول.",
  "Select a record to edit its content.": "د سمون لپاره یو ریکارډ وټاکئ.",
  "Update the fields below. Multilingual values are stored separately.": "لاندې ساحې سمې کړئ. څوژبیز ارزښتونه جلا خوندي کېږي.",
  "Manage company details, homepage content, navigation, footer information and SEO.": "د شرکت جزیات، د کورپاڼې منځپانګه، مېنو، فوټر او SEO مدیریت کړئ.",
  "Main homepage introduction and calls to action.": "د کورپاڼې اصلي پېژندنه او د اقدام تڼۍ.",
  "Homepage organization introduction and imagery.": "په کورپاڼه کې د ادارې پېژندنه او انځورونه.",
  "Changes are saved only when you click the button.": "بدلونونه یوازې د خوندي کولو تڼۍ په کلیک سره ثبتېږي.",
  "Your website administration workspace is ready. Review publishing progress, media, messages and recent activity from here.": "د وېب‌سایټ اداري چاپېریال چمتو دی. د خپرېدو حالت، رسنۍ، پیغامونه او وروستي فعالیتونه له دې ځایه وګورئ.",
  "Contact form inbox": "د اړیکو فورم پیغامونه",
  "Current project publication coverage.": "د پروژو د خپرېدو اوسنی حالت.",
  "Common administration tasks.": "عام اداري کارونه.",
  "Latest recorded changes in the CMS.": "په CMS کې وروستي ثبت شوي بدلونونه.",
  "Record volume by module.": "په هره برخه کې د ریکارډونو شمېر.",

  "published": "خپور شوی",
  "Website services": "د وېب‌سایټ خدمتونه",
  "Partner records": "د شریکانو ریکارډونه",
  "Stored assets": "ساتل شوې رسنۍ",
  "Live data": "ژوندۍ معلومات",
  "Published projects": "خپرې شوې پروژې",
  "Other project states": "د پروژو نور حالتونه",
  "Total projects": "ټولې پروژې",
  "Loading recent activity…": "وروستي فعالیتونه پورته کېږي…",
  "No activity has been recorded yet.": "تر اوسه کوم فعالیت نه دی ثبت شوی.",
  "Upload an image to Cloudinary through the existing Media Library API, or paste an existing secure Cloudinary URL below.": "د موجود Media Library API له لارې Cloudinary ته انځور پورته کړئ، یا لاندې د Cloudinary موجود خوندي URL ولیکئ.",
  "Email changes remain controlled by Users & Roles.": "د ایمیل بدلون لا هم د Users & Roles له برخې اداره کېږي.",
  "You can paste a Cloudinary HTTPS image URL directly.": "تاسو کولی شئ د Cloudinary د انځور HTTPS URL مستقیم ولیکئ.",
  "Change your password without affecting your profile preferences.": "خپل پټنوم د پروفایل د غوره توبونو له بدلون پرته بدل کړئ.",
  "Copy asset URLs for use in CMS content fields.": "د CMS د منځپانګې په برخو کې د کارولو لپاره د فایلونو URL کاپي کړئ.",
  "Upload your first image or PDF.": "خپل لومړی انځور یا PDF پورته کړئ.",
  "Images and PDF documents up to 10 MB are stored in Cloudinary.": "تر ۱۰ MB پورې انځورونه او PDF اسناد په Cloudinary کې ساتل کېږي.",
  "JPEG, PNG, WebP, AVIF, GIF or PDF · maximum 10 MB": "JPEG، PNG، WebP، AVIF، GIF یا PDF · اعظمي ۱۰ MB",
  "Review and manage messages submitted through the public website contact form.": "د عامه وېب‌سایټ د اړیکې فورم له لارې استول شوي پیغامونه وګورئ او اداره یې کړئ.",
  "Select a message to open its details.": "د جزیاتو لپاره یو پیغام وټاکئ.",
  "Reply by email": "د ایمیل له لارې ځواب",
  "Subject": "موضوع",
  "Received": "ترلاسه شوی",
  "Website inquiry": "د وېب‌سایټ پوښتنه",
  "Add a private note for administrators…": "د مدیرانو لپاره شخصي یادښت اضافه کړئ…",
  "Create CMS administrators and editors, manage roles, and control account access.": "د CMS مدیران او ایډیټران جوړ کړئ، رولونه اداره کړئ او د حساب لاسرسی کنټرول کړئ.",
  "Accounts with access to administration.": "هغه حسابونه چې مدیریت ته لاسرسی لري.",
  "No users found.": "هیڅ کارن ونه موندل شو.",
  "Configure identity, credentials and CMS role.": "هویت، د ننوتلو معلومات او د CMS رول تنظیم کړئ.",
  "Allow this user to sign in.": "دې کارن ته د ننوتلو اجازه ورکړئ.",
  "Prompt the user to set a new password on next sign-in.": "په بل ننوتلو کې له کارن څخه د نوي پټنوم غوښتنه وکړئ.",
  "Administration history": "د مدیریت تاریخچه",
  "Review recorded administrative actions by user, resource, and date.": "ثبت شوي اداري فعالیتونه د کارن، سرچینې او نېټې له مخې وګورئ.",
  "Most recent administrative events are shown first.": "تر ټولو وروستي اداري فعالیتونه لومړی ښودل کېږي.",
  "Theme color hex value": "د قالب د رنګ کوډ",
  "Theme": "قالب",
  "Content Management System": "د منځپانګې مدیریت سیستم",
  "Secure administration": "خوندي مدیریت",
  "Manage your website from one professional workspace.": "خپل وېب‌سایټ له یوه مسلکي کاري چاپېریال څخه اداره کړئ.",
  "Control projects, services, media, contact messages, multilingual content and website settings.": "پروژې، خدمتونه، رسنۍ، د اړیکې پیغامونه، څوژبیزه منځپانګه او د وېب‌سایټ تنظیمات اداره کړئ.",
  "Maintain published website information.": "د وېب‌سایټ خپاره شوي معلومات اداره کړئ.",
  "Media library": "د رسنیو کتابتون",
  "Organize Cloudinary-backed assets.": "په Cloudinary کې ساتل شوې رسنۍ تنظیم کړئ.",
  "Administrative control": "اداري کنټرول",
  "Role-based access and audit history.": "د رول پر بنسټ لاسرسی او د فعالیتونو تاریخچه.",
  "Authorized administrators only": "یوازې مجاز مدیران",
  "Administrator access": "د مدیر ننوتل",
  "Enter your administrator credentials to continue.": "د دوام لپاره د مدیر د ننوتلو معلومات ولیکئ.",
  "Email address": "د ایمیل پته",
  "Your session is protected by the existing CMS authentication system.": "ستاسو ناسته د CMS د موجود تصدیق سیستم له خوا خوندي ده.",
  "Account security": "د حساب امنیت",
  "Your administrator requires a new password before you can continue to the CMS.": "CMS ته له دوام مخکې باید نوی پټنوم وټاکئ.",
  "Open navigation": "مېنو پرانیستل",
  "CMS summary": "د CMS لنډیز",
  "Check visitor messages": "د لیدونکو پیغامونه وګورئ",
  "Close navigation": "مېنو بندول",
  "Tabiat Gran CMS dashboard": "د Tabiat Gran CMS ډشبورډ",
  "Admin navigation": "د مدیریت مېنو",
  "Open account menu": "د حساب مېنو پرانیستل",
  "Media record removed. The Cloudinary asset was already missing.": "د رسنۍ ریکارډ لرې شو؛ د Cloudinary فایل لا مخکې موجود نه و.",
  "Media deleted from Cloudinary and the CMS library.": "رسنۍ له Cloudinary او CMS کتابتون څخه حذف شوه.",
  "Delete failed": "حذف ناکام شو",
  "Media uploaded successfully.": "رسنۍ په بریالیتوب پورته شوه.",
  "Profile photo uploaded. Save your profile to use it for your account.": "د پروفایل عکس پورته شو. د حساب لپاره یې د کارولو په موخه پروفایل خوندي کړئ.",
  "New passwords do not match.": "نوي پټنومونه سره سمون نه خوري.",
  "Content record": "د منځپانګې ریکارډ",
  "One Cloudinary URL per line": "په هره کرښه کې یو Cloudinary URL",
  "Control public website menu labels in English, Dari and Pashto.": "د عامه وېب‌سایټ د مېنو نومونه په انګلیسي، دري او پښتو ژبو کې تنظیم کړئ.",
  "Core identity, contact details, branding and office information.": "اصلي هویت، د اړیکو معلومات، نښه او د دفتر معلومات.",
  "Define categories used to organize projects.": "هغه کټګورۍ تعریف کړئ چې د پروژو د تنظیم لپاره کارېږي.",
  "Edit organization information and footer labels displayed across the public website.": "د ادارې معلومات او د فوټر نومونه چې په عامه وېب‌سایټ کې ښودل کېږي سم کړئ.",
  "Edit the hero and about sections shown on the public homepage.": "د کورپاڼې اصلي او زموږ په اړه برخې سمې کړئ.",
  "Keep the current format expected by the backend settings model.": "هغه اوسنی فارمټ وساتئ چې د بک‌اېنډ د تنظیماتو ماډل یې تمه لري.",
  "Manage UN agencies, INGOs, national NGOs and government partners.": "د ملګرو ملتونو ادارې، نړیوالې موسسې، ملي موسسې او دولتي شریکان اداره کړئ.",
  "Manage headline numbers such as years of experience, projects and beneficiaries.": "مهمې شمېرې لکه د تجربې کلونه، پروژې او ګټه‌اخیستونکي اداره کړئ.",
  "Manage metadata used by search engines and social platforms.": "هغه مېټاډاټا اداره کړئ چې د لټون ماشینونو او ټولنیزو شبکو لپاره کارېږي.",
  "Manage partner/client testimonials displayed on the site.": "د شریکانو او مراجعینو نظرونه چې په وېب‌سایټ کې ښودل کېږي اداره کړئ.",
  "Manage services presented on the public website.": "هغه خدمتونه اداره کړئ چې په عامه وېب‌سایټ کې ښودل کېږي.",
  "Manage the multilingual project portfolio, galleries, outcomes and publication state.": "د پروژو څوژبیز پورتفولیو، ګالریانې، پایلې او د خپرېدو حالت اداره کړئ.",
  "Message status filter": "د پیغام د حالت فلټر",
  "Paste the URL of the selected hero image from Media Library.": "د Media Library څخه د ټاکل شوي اصلي انځور URL ولیکئ.",
  "Settings sections": "د تنظیماتو برخې",
  "Use a square icon asset where possible.": "که امکان وي مربع آیکن وکاروئ.",
  "Use an asset URL from the Media Library.": "د Media Library د فایل URL وکاروئ.",
  "Used when the website is shared on social platforms.": "کله چې وېب‌سایټ په ټولنیزو شبکو کې شریکېږي کارول کېږي.",
  "Unable to load dashboard": "ډشبورډ پورته نه شو",
  "Unable to load settings": "تنظیمات پورته نه شول",
  "Unable to load data": "معلومات پورته نه شول",
  "Unable to load messages": "پیغامونه پورته نه شول",
  "Unable to load media": "رسنۍ پورته نه شوې",
  "Unable to load audit log": "د فعالیتونو ثبت پورته نه شو",
  "Unable to update profile": "پروفایل تازه نه شو",
  "Unable to change password": "پټنوم بدل نه شو",
  "Profile image upload failed": "د پروفایل انځور پورته کول ناکام شول",
  "Sign in failed": "ننوتل ناکام شول",
  "New passwords do not match": "نوي پټنومونه سره سمون نه خوري",
  "Save failed": "خوندي کول ناکام شول",
  "Update failed": "تازه کول ناکام شول",
  "Upload failed": "پورته کول ناکام شول",
  "Account not found": "حساب ونه موندل شو",
  "A record with this unique value already exists": "د دې ځانګړي ارزښت سره ریکارډ لا مخکې شته",
  "Cloudinary did not confirm deletion": "Cloudinary د فایل حذف تایید نه کړ",
  "Cloudinary environment variables are not configured": "د Cloudinary چاپېریالي متغیرونه نه دي تنظیم شوي",
  "Cloudinary upload failed": "Cloudinary ته پورته کول ناکام شول",
  "Current password is incorrect": "اوسنی پټنوم ناسم دی",
  "File exceeds 10 MB": "د فایل اندازه له ۱۰ MB څخه زیاته ده",
  "File is required": "فایل اړین دی",
  "Forbidden": "لاسرسی منع دی",
  "Invalid credentials": "د ننوتلو معلومات ناسم دي",
  "Invalid email or password": "ایمیل یا پټنوم ناسم دی",
  "Invalid message update": "د پیغام تازه کول معتبر نه دي",
  "Invalid request data": "د غوښتنې معلومات معتبر نه دي",
  "Not found": "مورد ونه موندل شو",
  "Unknown resource": "نامعلومه سرچینه",
  "Unsupported file type": "د فایل ډول نه ملاتړ کېږي",
  "Your role cannot publish content": "ستاسو رول د منځپانګې د خپرولو اجازه نه لري",
  "Create": "جوړول",
  "Update": "تازه کول",
  "Untitled record": "بې سرلیکه ریکارډ",
  "Enter your password": "خپل پټنوم ولیکئ",
  "Uploaded media": "پورته شوې رسنۍ",
  "Settings section navigation": "د تنظیماتو د برخو مېنو",
  "Selected media preview": "د ټاکل شوې رسنۍ مخکتنه",
  "AUTH_SECRET must be at least 32 characters": "د سیستم امنیتي کیلي باید لږ تر لږه ۳۲ توري ولري",
  "CMS data unavailable": "د CMS معلومات شتون نه لري",
  "MONGODB_URI is not configured": "د MongoDB ډیټابېس اړیکه نه ده تنظیم شوې",
  "New password must be different from the current password": "نوی پټنوم باید له اوسني پټنوم څخه توپیر ولري",
  "Origin not allowed": "د دې غوښتنې سرچینه اجازه نه لري",
  "Password change required": "د پټنوم بدلول اړین دي",
  "Please check the form fields": "مهرباني وکړئ د فورم ساحې وګورئ",
  "Projects unavailable": "پروژې شتون نه لري",
  "Too many login attempts. Try again later.": "د ننوتلو هڅې ډېرې شوې. وروسته بیا هڅه وکړئ.",
  "Too many messages. Try again later.": "ډېر پیغامونه لېږل شوي. وروسته بیا هڅه وکړئ.",
  "Unable to sign in": "حساب ته ننوتل ونه شول",
  "Unable to submit message": "د پیغام لېږل ونه شول",
  "Unauthorized": "تاسو د لاسرسي اجازه نه لرئ",
  "Use a new password of 10–72 characters.": "له ۱۰ څخه تر ۷۲ تورو پورې نوی پټنوم وکاروئ.",
  "Validation failed": "اعتبار سنجونه ناکامه شوه",
  "You cannot delete your own account": "تاسو خپل حساب نه شئ حذف کولی",
  "You cannot disable or demote your own account": "تاسو خپل حساب نه شئ غیرفعالولی یا یې د لاسرسي کچه ټیټولی",
};

const dictionaries: Record<Exclude<AdminLanguage, "en">, Record<string, string>> = { fa, ps };

function safeLanguage(value: string | null | undefined): AdminLanguage {
  return value === "fa" || value === "ps" ? value : "en";
}

function safeTheme(value: string | null | undefined): AdminThemeMode {
  return value === "dark" || value === "system" ? value : "light";
}

function safeAccent(value: string | null | undefined) {
  return value && /^#[0-9a-fA-F]{6}$/.test(value) ? value : DEFAULT_ACCENT;
}

type PreferencesContextValue = {
  language: AdminLanguage;
  themeMode: AdminThemeMode;
  themeColor: string;
  setLanguage: (language: AdminLanguage) => void;
  setThemeMode: (mode: AdminThemeMode) => void;
  setThemeColor: (color: string) => void;
  applyUserPreferences: (preferences: { language?: string; themeMode?: string; themeColor?: string }) => void;
  direction: "ltr" | "rtl";
  locale: string;
  t: (text: string) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

function applyToDocument(language: AdminLanguage, themeMode: AdminThemeMode, themeColor: string) {
  if (typeof document === "undefined") return;
  const root = document.documentElement;
  const dark = themeMode === "dark" || (themeMode === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches);
  root.lang = language === "fa" ? "fa-AF" : language === "ps" ? "ps-AF" : "en";
  root.dir = language === "en" ? "ltr" : "rtl";
  root.dataset.adminLang = language;
  root.dataset.theme = dark ? "dark" : "light";
  root.style.setProperty("--primary", themeColor);
  root.style.setProperty("--primary-hover", `color-mix(in srgb, ${themeColor} 86%, ${dark ? "white" : "black"})`);
  root.style.setProperty("--primary-soft", `color-mix(in srgb, ${themeColor} 14%, var(--panel))`);
}

export function AdminPreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AdminLanguage>("en");
  const [themeMode, setThemeModeState] = useState<AdminThemeMode>("light");
  const [themeColor, setThemeColorState] = useState(DEFAULT_ACCENT);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const nextLanguage = safeLanguage(localStorage.getItem("tg-cms-language"));
    const legacyTheme = localStorage.getItem("tg-cms-theme");
    const nextTheme = safeTheme(localStorage.getItem("tg-cms-theme-mode") || legacyTheme);
    const nextColor = safeAccent(localStorage.getItem("tg-cms-theme-color"));
    setLanguageState(nextLanguage);
    setThemeModeState(nextTheme);
    setThemeColorState(nextColor);
    applyToDocument(nextLanguage, nextTheme, nextColor);
    setReady(true);
  }, []);

  useEffect(() => {
    if (!ready) return;
    applyToDocument(language, themeMode, themeColor);
    localStorage.setItem("tg-cms-language", language);
    localStorage.setItem("tg-cms-theme-mode", themeMode);
    localStorage.setItem("tg-cms-theme", themeMode === "dark" ? "dark" : "light");
    localStorage.setItem("tg-cms-theme-color", themeColor);
  }, [language, themeMode, themeColor, ready]);

  useEffect(() => {
    if (themeMode !== "system") return;
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const handler = () => applyToDocument(language, themeMode, themeColor);
    media.addEventListener("change", handler);
    return () => media.removeEventListener("change", handler);
  }, [language, themeMode, themeColor]);

  const setLanguage = useCallback((value: AdminLanguage) => setLanguageState(safeLanguage(value)), []);
  const setThemeMode = useCallback((value: AdminThemeMode) => setThemeModeState(safeTheme(value)), []);
  const setThemeColor = useCallback((value: string) => setThemeColorState(safeAccent(value)), []);
  const applyUserPreferences = useCallback((preferences: { language?: string; themeMode?: string; themeColor?: string }) => {
    setLanguageState(safeLanguage(preferences.language));
    setThemeModeState(safeTheme(preferences.themeMode));
    setThemeColorState(safeAccent(preferences.themeColor));
  }, []);
  const t = useCallback((text: string) => language === "en" ? text : dictionaries[language][text] || text, [language]);
  const direction: "ltr" | "rtl" = language === "en" ? "ltr" : "rtl";
  const locale = language === "fa" ? "fa-AF" : language === "ps" ? "ps-AF" : "en-US";

  const value = useMemo(() => ({ language, themeMode, themeColor, setLanguage, setThemeMode, setThemeColor, applyUserPreferences, direction, locale, t }), [language, themeMode, themeColor, setLanguage, setThemeMode, setThemeColor, applyUserPreferences, direction, locale, t]);
  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function useAdminPreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("useAdminPreferences must be used inside AdminPreferencesProvider");
  return context;
}
